import { SIGN_TYPE } from './constants';
import { prepare } from './prepare';

// ── Field Type Factories (inlined from former fieldTypes.ts) ─────
const fieldFactory =
  (type: string, optionalData?: unknown) =>
  (
    fromField: string | string[] | null,
    toField?: string | null,
    processor: unknown = null,
    optional = false,
  ) => ({
    field: toField ?? (typeof fromField === 'string' ? fromField : null),
    name: fromField,
    optional,
    optionalData: optionalData,
    processor,
    type,
  });

const fieldsType = {
  aliasName: (data: unknown) => fieldFactory('aliasName', data),
  aliasOrAddress: (data: unknown) => fieldFactory('aliasOrAddress', data),
  asset: (_data?: unknown) => fieldFactory('assetId'),
  asset_script: (_data?: unknown) => fieldFactory('asset_script'),
  assetDescription: (_data?: unknown) => fieldFactory('assetDescription'),
  assetName: (_data?: unknown) => fieldFactory('assetName'),
  attachment: (_data?: unknown) => fieldFactory('attachment'),
  boolean: (_data?: unknown) => fieldFactory('boolean'),
  call: (_data?: unknown) => fieldFactory('call'),
  data: (_data?: unknown) => fieldFactory('data'),
  fromData: (_data?: unknown) => fieldFactory('fromData'),
  money: (_data?: unknown) => fieldFactory('money'),
  number: (_data?: unknown) => fieldFactory('number'),
  numberLike: (_data?: unknown) => fieldFactory('numberLike'),
  orderType: (_data?: unknown) => fieldFactory('orderType'),
  payment: (_data?: unknown) => fieldFactory('payment'),
  precision: (_data?: unknown) => fieldFactory('precision'),
  publicKey: (_data?: unknown) => fieldFactory('publicKey'),
  required: (_data?: unknown) => fieldFactory('required'),
  script: (_data?: unknown) => fieldFactory('script'),
  string: (_data?: unknown) => fieldFactory('string'),
  timestamp: (_data?: unknown) => fieldFactory('timestamp'),
  transfers: (data?: unknown) => fieldFactory('transfers', data),
} as const;

const { processors } = prepare;

export const getValidateSchema = (networkByte: number) => {
  return {
    [SIGN_TYPE.MATCHER_ORDERS]: [
      fieldsType.string()('senderPublicKey', null, null, true),
      fieldsType.timestamp()('timestamp', null, processors.timestamp),
    ],
    [SIGN_TYPE.AUTH]: [
      fieldsType.string()('prefix', null, processors.addValue('DCCWalletAuthentication'), true),
      fieldsType.string()('host'),
      fieldsType.string()('data'),
    ],
    [SIGN_TYPE.COINOMAT_CONFIRMATION]: [
      fieldsType.string()('prefix', null, processors.addValue('Coinomat'), true),
      fieldsType.timestamp()('timestamp', null, processors.timestamp),
    ],
    [SIGN_TYPE.DCC_CONFIRMATION]: [
      fieldsType.publicKey()('publicKey', 'publicKey', null, true),
      fieldsType.timestamp()('timestamp', null, processors.timestamp),
    ],
    [SIGN_TYPE.CREATE_ORDER]: [
      fieldsType.string()('senderPublicKey', null, null, true),
      fieldsType.string()('matcherPublicKey'),
      fieldsType.money()('amount', 'amountAsset', processors.moneyToAssetId),
      fieldsType.money()('price', 'priceAsset', processors.moneyToAssetId),
      fieldsType.orderType()('orderType'),
      fieldsType.money()('amount', 'amount', processors.toBigNumber),
      fieldsType.fromData()(null, 'price', processors.toOrderPrice),
      fieldsType.money()('matcherFee', null, processors.toBigNumber),
      fieldsType.timestamp()('expiration', null, processors.expiration),
      fieldsType.timestamp()('timestamp', null, processors.timestamp),
      fieldsType.number()(
        'chainId',
        null,
        processors.addValue(() => networkByte),
        true,
      ),
    ],
    [SIGN_TYPE.CANCEL_ORDER]: [
      fieldsType.string()('senderPublicKey', null, null, true),
      fieldsType.string()('id', 'orderId'),
      fieldsType.number()(
        'chainId',
        null,
        processors.addValue(() => networkByte),
        true,
      ),
    ],
    [SIGN_TYPE.ISSUE]: [
      fieldsType.string()('senderPublicKey', null, null, true),
      fieldsType.assetName()('name'),
      fieldsType.assetDescription()('description'),
      fieldsType.number()(
        'chainId',
        null,
        processors.addValue(() => networkByte),
        true,
      ),
      fieldsType.numberLike()('quantity', null, processors.toBigNumber),
      fieldsType.precision()('precision'),
      fieldsType.boolean()('reissuable'),
      fieldsType.script()('script', null, processors.orString, true),
      fieldsType.numberLike()('fee', null, processors.toBigNumber),
      fieldsType.timestamp()('timestamp', null, processors.timestamp),
    ],
    [SIGN_TYPE.REISSUE]: [
      fieldsType.string()('senderPublicKey', null, null, true),
      fieldsType.number()(
        'chainId',
        null,
        processors.addValue(() => networkByte),
        true,
      ),
      fieldsType.asset()('assetId'),
      fieldsType.numberLike()('quantity', null, processors.toBigNumber),
      fieldsType.boolean()('reissuable'),
      fieldsType.numberLike()('fee', null, processors.toBigNumber),
      fieldsType.timestamp()('timestamp', null, processors.timestamp),
    ],
    [SIGN_TYPE.EXCHANGE]: [
      fieldsType.number()(
        'chainId',
        null,
        processors.addValue(() => networkByte),
        true,
      ),
      fieldsType.string()('senderPublicKey', null, null, true),
      fieldsType.timestamp()('timestamp', null, processors.timestamp),
      fieldsType.numberLike()('fee', null, processors.toBigNumber),
      fieldsType.fromData()('buyOrder'),
      fieldsType.fromData()('sellOrder'),
      fieldsType.numberLike()('amount', 'amount', processors.toBigNumber),
      fieldsType.numberLike()('price', 'price', processors.toBigNumber),
      fieldsType.numberLike()('buyMatcherFee', 'buyMatcherFee', processors.toBigNumber),
      fieldsType.numberLike()('sellMatcherFee', 'sellMatcherFee', processors.toBigNumber),
    ],
    [SIGN_TYPE.BURN]: [
      fieldsType.string()('senderPublicKey', null, null, true),
      fieldsType.number()(
        'chainId',
        null,
        processors.addValue(() => networkByte),
        true,
      ),
      fieldsType.asset()('assetId'),
      fieldsType.numberLike()(['amount', 'quantity'], 'amount', processors.toBigNumber),
      fieldsType.numberLike()('fee', null, processors.toBigNumber),
      fieldsType.timestamp()('timestamp', null, processors.timestamp),
    ],
    [SIGN_TYPE.UPDATE_ASSET_INFO]: [
      fieldsType.number()(
        'type',
        null,
        processors.addValue(() => SIGN_TYPE.UPDATE_ASSET_INFO),
        true,
      ),
      fieldsType.string()('senderPublicKey', null, null, true),
      fieldsType.number()(
        'chainId',
        null,
        processors.addValue(() => networkByte),
        true,
      ),
      fieldsType.numberLike()('fee', null, processors.toBigNumber),
      fieldsType.timestamp()('timestamp', null, processors.timestamp),
      fieldsType.asset()('assetId'),
      fieldsType.assetName()('name'),
      fieldsType.assetDescription()('description'),
    ],
    [SIGN_TYPE.SPONSORSHIP]: [
      fieldsType.number()(
        'chainId',
        null,
        processors.addValue(() => networkByte),
        true,
      ),
      fieldsType.string()('senderPublicKey', null, null, true),
      fieldsType.money()('minSponsoredAssetFee', 'assetId', processors.moneyToAssetId),
      fieldsType.numberLike()('minSponsoredAssetFee', null, processors.toBigNumber),
      fieldsType.numberLike()('fee', null, processors.toBigNumber),
      fieldsType.timestamp()('timestamp', null, processors.timestamp),
    ],
    [SIGN_TYPE.TRANSFER]: [
      fieldsType.string()('senderPublicKey', null, null, true),
      fieldsType.number()(
        'chainId',
        null,
        processors.addValue(() => networkByte),
        true,
      ),
      fieldsType.money()('amount', 'assetId', processors.moneyToAssetId),
      fieldsType.required()('amount', null, processors.toBigNumber),
      fieldsType.money()('fee', 'feeAssetId', processors.moneyToAssetId),
      fieldsType.required()('fee', 'fee', processors.toBigNumber),
      fieldsType.timestamp()('timestamp', null, processors.timestamp),
      fieldsType.aliasOrAddress(networkByte)('recipient'),
      fieldsType.attachment()('attachment', null, processors.orString, true),
    ],
    [SIGN_TYPE.LEASE]: [
      fieldsType.string()('senderPublicKey', null, null, true),
      fieldsType.number()(
        'chainId',
        null,
        processors.addValue(() => networkByte),
        true,
      ),
      fieldsType.aliasOrAddress(networkByte)('recipient'),
      fieldsType.numberLike()('amount', null, processors.toBigNumber),
      fieldsType.numberLike()('fee', null, processors.toBigNumber),
      fieldsType.timestamp()('timestamp', null, processors.timestamp),
    ],
    [SIGN_TYPE.CANCEL_LEASING]: [
      fieldsType.string()('senderPublicKey', null, null, true),
      fieldsType.number()(
        'chainId',
        null,
        processors.addValue(() => networkByte),
        true,
      ),
      fieldsType.string()('leaseId', 'transactionId'),
      fieldsType.numberLike()('fee', null, processors.toBigNumber),
      fieldsType.timestamp()('timestamp', null, processors.timestamp),
    ],
    [SIGN_TYPE.CREATE_ALIAS]: [
      fieldsType.string()('senderPublicKey', null, null, true),
      fieldsType.number()(
        'chainId',
        null,
        processors.addValue(() => networkByte),
        true,
      ),
      fieldsType.aliasName(networkByte)('alias'),
      fieldsType.numberLike()('fee', null, processors.toBigNumber),
      fieldsType.timestamp()('timestamp', null, processors.timestamp),
    ],
    [SIGN_TYPE.MASS_TRANSFER]: [
      fieldsType.number()(
        'chainId',
        null,
        processors.addValue(() => networkByte),
        true,
      ),
      fieldsType.string()('senderPublicKey', null, null, true),
      fieldsType.money()('totalAmount', 'assetId', processors.moneyToAssetId),
      fieldsType.transfers(networkByte)(
        'transfers',
        null,
        processors.transfers(processors.noProcess, processors.toBigNumber),
      ),
      fieldsType.numberLike()('fee', null, processors.toBigNumber),
      fieldsType.attachment()('attachment', null, processors.orString, true),
      fieldsType.timestamp()('timestamp', null, processors.timestamp),
    ],
    [SIGN_TYPE.DATA]: [
      fieldsType.number()(
        'chainId',
        null,
        processors.addValue(() => networkByte),
        true,
      ),
      fieldsType.string()('senderPublicKey', null, null, true),
      fieldsType.numberLike()('fee', null, processors.toBigNumber),
      fieldsType.timestamp()('timestamp', null, processors.timestamp),
      fieldsType.data()('data'),
    ],
    [SIGN_TYPE.SET_SCRIPT]: [
      fieldsType.string()('senderPublicKey', null, null, true),
      fieldsType.numberLike()('fee', null, processors.toBigNumber),
      fieldsType.timestamp()('timestamp', null, processors.timestamp),
      fieldsType.number()(
        'chainId',
        null,
        processors.addValue(() => networkByte),
        true,
      ),
      fieldsType.script()('script'),
    ],
    [SIGN_TYPE.SET_ASSET_SCRIPT]: [
      fieldsType.string()('senderPublicKey', null, null, true),
      fieldsType.asset()('assetId'),
      fieldsType.numberLike()('fee', null, processors.toBigNumber),
      fieldsType.timestamp()('timestamp', null, processors.timestamp),
      fieldsType.number()(
        'chainId',
        null,
        processors.addValue(() => networkByte),
        true,
      ),
      fieldsType.asset_script()('script'),
    ],
    [SIGN_TYPE.SCRIPT_INVOCATION]: [
      fieldsType.number()(
        'type',
        null,
        processors.addValue(() => SIGN_TYPE.SCRIPT_INVOCATION),
        true,
      ),
      fieldsType.number()(
        'version',
        null,
        processors.addValue(() => 1),
        true,
      ),

      fieldsType.string()('senderPublicKey', null, null, true),
      fieldsType.aliasOrAddress(networkByte)('dApp'),
      fieldsType.call()('call', 'call', processors.callFunc, true),
      fieldsType.payment()('payment', null, processors.payments, true),
      fieldsType.numberLike()('fee', null, processors.toNumberString),
      fieldsType.numberLike()('fee', 'assetId', processors.moneyToAssetId),
      fieldsType.timestamp()('timestamp', null, processors.timestamp),
      fieldsType.number()(
        'chainId',
        null,
        processors.addValue(() => networkByte),
        true,
      ),
    ],
  };
};
